# Generated by Selenium IDE
from selenium import webdriver
from selenium.webdriver.common.by import By


class TestAddtocart():
    def setup_method(self, method):
        self.driver = webdriver.Chrome()
        self.vars = {}

    def open_home_page(self):
    # open home page
        self.driver.get("https://www.saucedemo.com/")
        self.driver.set_window_size(1440, 821)

    def login(self):
    # login
        self.driver.find_element(By.XPATH, "//input[@id=\'user-name\']").click()
        self.driver.find_element(By.XPATH, "//input[@id=\'user-name\']").send_keys("standard_user")
        self.driver.find_element(By.XPATH, "//input[@id=\'password\']").click()
        self.driver.find_element(By.XPATH, "//input[@id=\'password\']").send_keys("secret_sauce")
        self.driver.find_element(By.XPATH, "//input[@id=\'login-button\']").click()

    def add_to_cart(self):
    # add to cart
        self.driver.find_element(By.XPATH, "//button[@id=\'add-to-cart-sauce-labs-backpack\']").click()
        self.driver.find_element(By.XPATH, "//div[@id=\'shopping_cart_container\']/a").click()

    def fill_checkout_form(self):
    # fill checkout form
        self.driver.find_element(By.XPATH, "//button[@id=\'checkout\']").click()
        self.driver.find_element(By.XPATH, "//input[@id=\'first-name\']").click()
        self.driver.find_element(By.XPATH, "//input[@id=\'first-name\']").send_keys("Alex")
        self.driver.find_element(By.XPATH, "//input[@id=\'last-name\']").click()
        self.driver.find_element(By.XPATH, "//input[@id=\'last-name\']").send_keys("Test")
        self.driver.find_element(By.XPATH, "//input[@id=\'postal-code\']").click()
        self.driver.find_element(By.XPATH, "//input[@id=\'postal-code\']").send_keys("123")
        self.driver.find_element(By.XPATH, "//div[@id=\'checkout_info_container\']/div/form").click()
        self.driver.find_element(By.XPATH, "//input[@id=\'continue\']").click()

    def submit_checkout(self):
    # submit checkout
        self.driver.find_element(By.XPATH, "//button[@id=\'finish\']").click()

    def back_to_products_page(self):
    # back to products page
        self.driver.find_element(By.XPATH, "//button[@id=\'back-to-products\']").click()

    def open_menu(self):
    # open menu
        self.driver.find_element(By.XPATH, "//button[@id=\'react-burger-menu-btn\']").click()

    def logout(self):
    # logout
        self.driver.find_element(By.XPATH, "//a[contains(text(),\'Logout\')]").click()

    def test_addtocart(self):
        self.open_home_page()
        self.login()
        self.add_to_cart()
        self.fill_checkout_form()
        self.submit_checkout()
        self.back_to_products_page()
        self.open_menu()
        self.logout()

    def teardown_method(self, method):
        self.driver.quit()











