# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTestloginlogout():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_testloginlogout(self):
    self.driver.get("https://practicetestautomation.com/practice-test-login/")
    self.driver.set_window_size(1440, 821)
    self.driver.find_element(By.XPATH, "//input[@id=\'username\']").send_keys("student")
    self.driver.find_element(By.XPATH, "//input[@id=\'password\']").send_keys("Password123")
    self.driver.find_element(By.XPATH, "//button[@id=\'submit\']").click()
    self.driver.find_element(By.XPATH, "//a[contains(text(),\'Log out\')]").click()
  
