# Generated by Selenium IDE

from selenium import webdriver
from selenium.webdriver.common.by import By


class Test_login_logout():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_login_logout(self):
    self.driver.get("https://practicetestautomation.com/practice-test-login/")
    self.driver.set_window_size(1440, 821)
    self.driver.find_element(By.XPATH, "//input[@id=\'username\']").send_keys("student")
    self.driver.find_element(By.XPATH, "//input[@id=\'password\']").send_keys("Password123")
    self.driver.find_element(By.XPATH, "//button[@id=\'submit\']").click()
    self.driver.find_element(By.XPATH, "//a[contains(text(),\'Log out\')]").click()
  
